# Generated by Django 4.1.1 on 2022-11-25 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(default=True)),
                ('description', models.TextField(default=True)),
                ('categories', models.ManyToManyField(related_name='photos', to='blog0.category')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        
    ]
