# Generated by Django 4.1.1 on 2022-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog0', '0002_photo_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='contact',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='categories',
            field=models.ManyToManyField(default=True, related_name='photos', to='blog0.category'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
