# Generated by Django 4.1.1 on 2022-11-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog0', '0003_photo_contact_alter_photo_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
