# Generated by Django 4.1.1 on 2022-11-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog0', '0004_alter_photo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
