# Generated by Django 4.1.1 on 2022-11-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog0', '0005_alter_photo_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
