# Generated by Django 4.1.1 on 2022-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog0', '0006_alter_photo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='images',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
