# Generated by Django 4.1.1 on 2022-12-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog0', '0007_photo_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='images',
        ),
    ]
