# Generated by Django 4.1.1 on 2022-12-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog0', '0009_photo_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='active',
            field=models.BooleanField(),
        ),
    ]
